// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void CreateLobbyHandler(ReducerEvent reducerEvent, uint id, string kelas, string materi, string pertemuan, System.Collections.Generic.List<ulong> participants);
		public static event CreateLobbyHandler OnCreateLobbyEvent;

		public static void CreateLobby(uint id, string kelas, string materi, string pertemuan, System.Collections.Generic.List<ulong> participants)
		{
			var _argArray = new object[] {id, kelas, materi, pertemuan, participants};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "create_lobby",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "create_lobby")]
		public static bool OnCreateLobby(ClientApi.Event dbEvent)
		{
			if(OnCreateLobbyEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).CreateLobbyArgs;
				OnCreateLobbyEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(uint)args.Id
					,(string)args.Kelas
					,(string)args.Materi
					,(string)args.Pertemuan
					,(System.Collections.Generic.List<ulong>)args.Participants
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "create_lobby")]
		public static void CreateLobbyDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new CreateLobbyArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U32), reader);
			args.Id = args_0_value.AsU32();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Kelas = args_1_value.AsString();
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Materi = args_2_value.AsString();
			var args_3_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Pertemuan = args_3_value.AsString();
			var args_4_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreateArrayType(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64)), reader);
			args.Participants = ((System.Func<System.Collections.Generic.List<ulong>>)(() => {
				var vec0 = new System.Collections.Generic.List<ulong>();
				var vec0_source = args_4_value.AsArray();
				foreach(var entry in vec0_source!)
				{
					vec0.Add(entry.AsU64());
				}
				return vec0;
			}))();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.CreateLobby, "create_lobby", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class CreateLobbyArgsStruct
	{
		public uint Id;
		public string Kelas;
		public string Materi;
		public string Pertemuan;
		public System.Collections.Generic.List<ulong> Participants;
	}

}
