// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void FilterLobbiesHandler(ReducerEvent reducerEvent, string kelas, string materi, string pertemuan);
		public static event FilterLobbiesHandler OnFilterLobbiesEvent;

		public static void FilterLobbies(string kelas, string materi, string pertemuan)
		{
			var _argArray = new object[] {kelas, materi, pertemuan};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "filter_lobbies",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "filter_lobbies")]
		public static bool OnFilterLobbies(ClientApi.Event dbEvent)
		{
			if(OnFilterLobbiesEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).FilterLobbiesArgs;
				OnFilterLobbiesEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(string)args.Kelas
					,(string)args.Materi
					,(string)args.Pertemuan
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "filter_lobbies")]
		public static void FilterLobbiesDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new FilterLobbiesArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Kelas = args_0_value.AsString();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Materi = args_1_value.AsString();
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Pertemuan = args_2_value.AsString();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.FilterLobbies, "filter_lobbies", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class FilterLobbiesArgsStruct
	{
		public string Kelas;
		public string Materi;
		public string Pertemuan;
	}

}
