// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void InteractHandler(ReducerEvent reducerEvent, ulong entityId);
		public static event InteractHandler OnInteractEvent;

		public static void Interact(ulong entityId)
		{
			var _argArray = new object[] {entityId};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "interact",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "interact")]
		public static bool OnInteract(ClientApi.Event dbEvent)
		{
			if(OnInteractEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).InteractArgs;
				OnInteractEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(ulong)args.EntityId
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "interact")]
		public static void InteractDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new InteractArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.EntityId = args_0_value.AsU64();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.Interact, "interact", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class InteractArgsStruct
	{
		public ulong EntityId;
	}

}
