// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void MovePlayerHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbVector3 position, SpacetimeDB.Types.StdbVector2 direction, bool moving, bool sprinting);
		public static event MovePlayerHandler OnMovePlayerEvent;

		public static void MovePlayer(SpacetimeDB.Types.StdbVector3 position, SpacetimeDB.Types.StdbVector2 direction, bool moving, bool sprinting)
		{
			var _argArray = new object[] {position, direction, moving, sprinting};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "move_player",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "move_player")]
		public static bool OnMovePlayer(ClientApi.Event dbEvent)
		{
			if(OnMovePlayerEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).MovePlayerArgs;
				OnMovePlayerEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.Types.StdbVector3)args.Position
					,(SpacetimeDB.Types.StdbVector2)args.Direction
					,(bool)args.Moving
					,(bool)args.Sprinting
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "move_player")]
		public static void MovePlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new MovePlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector3.GetAlgebraicType(), reader);
			args.Position = (SpacetimeDB.Types.StdbVector3)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector2.GetAlgebraicType(), reader);
			args.Direction = (SpacetimeDB.Types.StdbVector2)(args_1_value);
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.Bool), reader);
			args.Moving = args_2_value.AsBool();
			var args_3_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.Bool), reader);
			args.Sprinting = args_3_value.AsBool();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.MovePlayer, "move_player", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class MovePlayerArgsStruct
	{
		public SpacetimeDB.Types.StdbVector3 Position;
		public SpacetimeDB.Types.StdbVector2 Direction;
		public bool Moving;
		public bool Sprinting;
	}

}
