// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void PublicChatMessageHandler(ReducerEvent reducerEvent, uint lobbyId, string message);
		public static event PublicChatMessageHandler OnPublicChatMessageEvent;

		public static void PublicChatMessage(uint lobbyId, string message)
		{
			var _argArray = new object[] {lobbyId, message};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "public_chat_message",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "public_chat_message")]
		public static bool OnPublicChatMessage(ClientApi.Event dbEvent)
		{
			if(OnPublicChatMessageEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).PublicChatMessageArgs;
				OnPublicChatMessageEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(uint)args.LobbyId
					,(string)args.Message
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "public_chat_message")]
		public static void PublicChatMessageDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new PublicChatMessageArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U32), reader);
			args.LobbyId = args_0_value.AsU32();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Message = args_1_value.AsString();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.PublicChatMessage, "public_chat_message", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class PublicChatMessageArgsStruct
	{
		public uint LobbyId;
		public string Message;
	}

}
