// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void SendPrivateMessageHandler(ReducerEvent reducerEvent, uint lobbyId, ulong senderId, ulong recipientId, string message);
		public static event SendPrivateMessageHandler OnSendPrivateMessageEvent;

		public static void SendPrivateMessage(uint lobbyId, ulong senderId, ulong recipientId, string message)
		{
			var _argArray = new object[] {lobbyId, senderId, recipientId, message};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "send_private_message",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "send_private_message")]
		public static bool OnSendPrivateMessage(ClientApi.Event dbEvent)
		{
			if(OnSendPrivateMessageEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).SendPrivateMessageArgs;
				OnSendPrivateMessageEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(uint)args.LobbyId
					,(ulong)args.SenderId
					,(ulong)args.RecipientId
					,(string)args.Message
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "send_private_message")]
		public static void SendPrivateMessageDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new SendPrivateMessageArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U32), reader);
			args.LobbyId = args_0_value.AsU32();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.SenderId = args_1_value.AsU64();
			var args_2_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.RecipientId = args_2_value.AsU64();
			var args_3_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.String), reader);
			args.Message = args_3_value.AsString();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.SendPrivateMessage, "send_private_message", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class SendPrivateMessageArgsStruct
	{
		public uint LobbyId;
		public ulong SenderId;
		public ulong RecipientId;
		public string Message;
	}

}
