// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void StopPlayerHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbVector3 position, SpacetimeDB.Types.StdbVector2 direction);
		public static event StopPlayerHandler OnStopPlayerEvent;

		public static void StopPlayer(SpacetimeDB.Types.StdbVector3 position, SpacetimeDB.Types.StdbVector2 direction)
		{
			var _argArray = new object[] {position, direction};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "stop_player",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "stop_player")]
		public static bool OnStopPlayer(ClientApi.Event dbEvent)
		{
			if(OnStopPlayerEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).StopPlayerArgs;
				OnStopPlayerEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.Types.StdbVector3)args.Position
					,(SpacetimeDB.Types.StdbVector2)args.Direction
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "stop_player")]
		public static void StopPlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new StopPlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector3.GetAlgebraicType(), reader);
			args.Position = (SpacetimeDB.Types.StdbVector3)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbVector2.GetAlgebraicType(), reader);
			args.Direction = (SpacetimeDB.Types.StdbVector2)(args_1_value);
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.StopPlayer, "stop_player", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class StopPlayerArgsStruct
	{
		public SpacetimeDB.Types.StdbVector3 Position;
		public SpacetimeDB.Types.StdbVector2 Direction;
	}

}
