// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void StopRotatePlayerHandler(ReducerEvent reducerEvent, SpacetimeDB.Types.StdbQuaternion rotation, float rotvalue);
		public static event StopRotatePlayerHandler OnStopRotatePlayerEvent;

		public static void StopRotatePlayer(SpacetimeDB.Types.StdbQuaternion rotation, float rotvalue)
		{
			var _argArray = new object[] {rotation, rotvalue};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "stop_rotate_player",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "stop_rotate_player")]
		public static bool OnStopRotatePlayer(ClientApi.Event dbEvent)
		{
			if(OnStopRotatePlayerEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).StopRotatePlayerArgs;
				OnStopRotatePlayerEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(SpacetimeDB.Types.StdbQuaternion)args.Rotation
					,(float)args.Rotvalue
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "stop_rotate_player")]
		public static void StopRotatePlayerDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new StopRotatePlayerArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.Types.StdbQuaternion.GetAlgebraicType(), reader);
			args.Rotation = (SpacetimeDB.Types.StdbQuaternion)(args_0_value);
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.F32), reader);
			args.Rotvalue = args_1_value.AsF32();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.StopRotatePlayer, "stop_rotate_player", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class StopRotatePlayerArgsStruct
	{
		public SpacetimeDB.Types.StdbQuaternion Rotation;
		public float Rotvalue;
	}

}
