// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using ClientApi;
using Newtonsoft.Json.Linq;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	public static partial class Reducer
	{
		public delegate void UpdateLobbyTimeLimitHandler(ReducerEvent reducerEvent, uint lobbyId, ulong newTimeLimit);
		public static event UpdateLobbyTimeLimitHandler OnUpdateLobbyTimeLimitEvent;

		public static void UpdateLobbyTimeLimit(uint lobbyId, ulong newTimeLimit)
		{
			var _argArray = new object[] {lobbyId, newTimeLimit};
			var _message = new SpacetimeDBClient.ReducerCallRequest {
				fn = "update_lobby_time_limit",
				args = _argArray,
			};
			SpacetimeDBClient.instance.InternalCallReducer(Newtonsoft.Json.JsonConvert.SerializeObject(_message, _settings));
		}

		[ReducerCallback(FunctionName = "update_lobby_time_limit")]
		public static bool OnUpdateLobbyTimeLimit(ClientApi.Event dbEvent)
		{
			if(OnUpdateLobbyTimeLimitEvent != null)
			{
				var args = ((ReducerEvent)dbEvent.FunctionCall.CallInfo).UpdateLobbyTimeLimitArgs;
				OnUpdateLobbyTimeLimitEvent((ReducerEvent)dbEvent.FunctionCall.CallInfo
					,(uint)args.LobbyId
					,(ulong)args.NewTimeLimit
				);
				return true;
			}
			return false;
		}

		[DeserializeEvent(FunctionName = "update_lobby_time_limit")]
		public static void UpdateLobbyTimeLimitDeserializeEventArgs(ClientApi.Event dbEvent)
		{
			var args = new UpdateLobbyTimeLimitArgsStruct();
			var bsatnBytes = dbEvent.FunctionCall.ArgBytes;
			using var ms = new System.IO.MemoryStream();
			ms.SetLength(bsatnBytes.Length);
			bsatnBytes.CopyTo(ms.GetBuffer(), 0);
			ms.Position = 0;
			using var reader = new System.IO.BinaryReader(ms);
			var args_0_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U32), reader);
			args.LobbyId = args_0_value.AsU32();
			var args_1_value = SpacetimeDB.SATS.AlgebraicValue.Deserialize(SpacetimeDB.SATS.AlgebraicType.CreatePrimitiveType(SpacetimeDB.SATS.BuiltinType.Type.U64), reader);
			args.NewTimeLimit = args_1_value.AsU64();
			dbEvent.FunctionCall.CallInfo = new ReducerEvent(ReducerType.UpdateLobbyTimeLimit, "update_lobby_time_limit", dbEvent.Timestamp, Identity.From(dbEvent.CallerIdentity.ToByteArray()), Address.From(dbEvent.CallerAddress.ToByteArray()), dbEvent.Message, dbEvent.Status, args);
		}
	}

	public partial class UpdateLobbyTimeLimitArgsStruct
	{
		public uint LobbyId;
		public ulong NewTimeLimit;
	}

}
