// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Config {
    pub version: u32,
    pub message_of_the_day: String,
}

impl TableType for Config {
    const TABLE_NAME: &'static str = "Config";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Config {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.version
    }
}

impl Config {
    #[allow(unused)]
    pub fn filter_by_version(version: u32) -> Option<Self> {
        Self::find(|row| row.version == version)
    }
    #[allow(unused)]
    pub fn filter_by_message_of_the_day(message_of_the_day: String) -> TableIter<Self> {
        Self::filter(|row| row.message_of_the_day == message_of_the_day)
    }
}
