// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct CreateLobbyArgs {
    pub id: u32,
    pub kelas: String,
    pub materi: String,
    pub pertemuan: String,
    pub participants: Vec<u64>,
}

impl Reducer for CreateLobbyArgs {
    const REDUCER_NAME: &'static str = "create_lobby";
}

#[allow(unused)]
pub fn create_lobby(
    id: u32,
    kelas: String,
    materi: String,
    pertemuan: String,
    participants: Vec<u64>,
) {
    CreateLobbyArgs {
        id,
        kelas,
        materi,
        pertemuan,
        participants,
    }
    .invoke();
}

#[allow(unused)]
pub fn on_create_lobby(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &u32, &String, &String, &String, &Vec<u64>)
        + Send
        + 'static,
) -> ReducerCallbackId<CreateLobbyArgs> {
    CreateLobbyArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let CreateLobbyArgs {
            id,
            kelas,
            materi,
            pertemuan,
            participants,
        } = __args;
        __callback(
            __identity,
            __addr,
            __status,
            id,
            kelas,
            materi,
            pertemuan,
            participants,
        );
    })
}

#[allow(unused)]
pub fn once_on_create_lobby(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &u32, &String, &String, &String, &Vec<u64>)
        + Send
        + 'static,
) -> ReducerCallbackId<CreateLobbyArgs> {
    CreateLobbyArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let CreateLobbyArgs {
            id,
            kelas,
            materi,
            pertemuan,
            participants,
        } = __args;
        __callback(
            __identity,
            __addr,
            __status,
            id,
            kelas,
            materi,
            pertemuan,
            participants,
        );
    })
}

#[allow(unused)]
pub fn remove_on_create_lobby(id: ReducerCallbackId<CreateLobbyArgs>) {
    CreateLobbyArgs::remove_on_reducer(id);
}
