// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct FilterLobbiesArgs {
    pub kelas: String,
    pub materi: String,
    pub pertemuan: String,
}

impl Reducer for FilterLobbiesArgs {
    const REDUCER_NAME: &'static str = "filter_lobbies";
}

#[allow(unused)]
pub fn filter_lobbies(kelas: String, materi: String, pertemuan: String) {
    FilterLobbiesArgs {
        kelas,
        materi,
        pertemuan,
    }
    .invoke();
}

#[allow(unused)]
pub fn on_filter_lobbies(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &String, &String, &String)
        + Send
        + 'static,
) -> ReducerCallbackId<FilterLobbiesArgs> {
    FilterLobbiesArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let FilterLobbiesArgs {
            kelas,
            materi,
            pertemuan,
        } = __args;
        __callback(__identity, __addr, __status, kelas, materi, pertemuan);
    })
}

#[allow(unused)]
pub fn once_on_filter_lobbies(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &String, &String, &String)
        + Send
        + 'static,
) -> ReducerCallbackId<FilterLobbiesArgs> {
    FilterLobbiesArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let FilterLobbiesArgs {
            kelas,
            materi,
            pertemuan,
        } = __args;
        __callback(__identity, __addr, __status, kelas, materi, pertemuan);
    })
}

#[allow(unused)]
pub fn remove_on_filter_lobbies(id: ReducerCallbackId<FilterLobbiesArgs>) {
    FilterLobbiesArgs::remove_on_reducer(id);
}
