// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Lobby {
    pub id: u32,
    pub identity: Identity,
    pub kelas: String,
    pub materi: String,
    pub pertemuan: String,
    pub participants: Vec<Identity>,
}

impl TableType for Lobby {
    const TABLE_NAME: &'static str = "Lobby";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Lobby {
    type PrimaryKey = u32;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl Lobby {
    #[allow(unused)]
    pub fn filter_by_id(id: u32) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_identity(identity: Identity) -> TableIter<Self> {
        Self::filter(|row| row.identity == identity)
    }
    #[allow(unused)]
    pub fn filter_by_kelas(kelas: String) -> TableIter<Self> {
        Self::filter(|row| row.kelas == kelas)
    }
    #[allow(unused)]
    pub fn filter_by_materi(materi: String) -> TableIter<Self> {
        Self::filter(|row| row.materi == materi)
    }
    #[allow(unused)]
    pub fn filter_by_pertemuan(pertemuan: String) -> TableIter<Self> {
        Self::filter(|row| row.pertemuan == pertemuan)
    }
    #[allow(unused)]
    pub fn filter_by_participants(participants: Vec<Identity>) -> TableIter<Self> {
        Self::filter(|row| row.participants == participants)
    }
}
